### PR TITLE
Add Window stats manager

### PR DESCRIPTION
**Pull request by deathart**

### CODE REVIEW

**Comment by simon-fraser** [comment]
@deathart Can you ensure the package is added to the `package.json` file and that there are no errors when running `npm run lint`

**Comment by deathart** [comment]
Oups, I add package

**Comment by deathart** [comment]
And run lint :)

**Comment by simon-fraser** [comment]
@deathart the application appears to fail build now `npm start` do you want to check why this is happening with the addition of the `electron-window-stats` module.

**Comment by deathart** [comment]
Resolved :)

**Pull request merged**
